language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install Cython"
  - "pip install -r requirements.txt"
script:
  - "python setup.py build_ext --inplace"
  - "flake8 src tests"
  - "nosetests -v"
